import argparse
import base64
import html
import json
import mimetypes
import os
import socket
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


MODEL = "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free"
FALLBACK_MODELS = ["google/gemini-2.0-flash-exp:free"]
DATASET_ROWS_URL = "https://datasets-server.huggingface.co/rows"
DATASET_PARAMS = {
    "dataset": "huggan/wikiart",
    "config": "default",
    "split": "train",
    "offset": 0,
}
OUTPUT_DIR = Path(__file__).resolve().parent
IMAGE_DIR = OUTPUT_DIR / "images"
RESULTS_JSON = OUTPUT_DIR / "results.json"
RESULTS_HTML = OUTPUT_DIR / "results.html"
REQUEST_TIMEOUT_SECONDS = 45


CLASSIFICATION_SCHEMA = {
    "name": "wikiart_image_classification",
    "strict": True,
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "has_human": {"type": "string", "enum": ["yes", "no"]},
            "has_animal": {"type": "string", "enum": ["yes", "no"]},
            "has_flower": {"type": "string", "enum": ["yes", "no"]},
            "looks_ai_generated": {"type": "string", "enum": ["yes", "no"]},
            "reason": {
                "type": "string",
                "description": "A short natural-language explanation with visual evidence and location words when possible.",
            },
            "ai_reason": {
                "type": "string",
                "description": "A short explanation of why the artwork looks AI-generated or clearly human-made.",
            },
        },
        "required": ["has_human", "has_animal", "has_flower", "looks_ai_generated", "reason", "ai_reason"],
    },
}


SYSTEM_PROMPT = """You classify WikiArt images using a fixed schema.

Definitions:
- has_human: "yes" if any human figure, face, body part, portrait, statue-like human, or clearly human silhouette is visible. Otherwise "no".
- has_animal: "yes" if any non-human animal, bird, fish, insect, horse, dog, mythical animal-like creature, or animal body part is visible. Otherwise "no".
- has_flower: "yes" if any flower blossom, bouquet, flowering plant, or clearly decorative floral motif is visible. Leaves alone are not enough. Otherwise "no".
- looks_ai_generated: Judge whether this artwork looks like it could have been generated by an AI image model (like Midjourney or DALL-E), based on visual characteristics such as texture consistency, anatomical accuracy, lighting uniformity, or surreal elements. Note: all images are actually historical human artworks.

Write a brief reason in English. Mention visual evidence and location words such as center, top-left, foreground, background, or right side when possible.
Keep reason and ai_reason under 25 words each.
For ai_reason, briefly explain why the image looks AI-generated or clearly human-made.
Return only the JSON object matching the schema."""


def encode_image_as_data_url(image_path: Path, mime_type: str | None = None) -> str:
    mime = mime_type or mimetypes.guess_type(image_path.name)[0] or "image/jpeg"
    encoded = base64.b64encode(image_path.read_bytes()).decode("utf-8")
    return f"data:{mime};base64,{encoded}"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def request_json(
    url: str,
    method: str = "GET",
    payload: dict | None = None,
    headers: dict | None = None,
    timeout: int = REQUEST_TIMEOUT_SECONDS,
) -> dict:
    data = None
    request_headers = headers or {}
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        request_headers = {"Content-Type": "application/json", **request_headers}
    request = urllib.request.Request(url, data=data, headers=request_headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} from {url}: {detail}") from exc
    except (TimeoutError, socket.timeout, urllib.error.URLError) as exc:
        raise RuntimeError(f"Request failed or timed out after {timeout}s for {url}: {exc}") from exc


def download_bytes(url: str) -> tuple[bytes, str]:
    request = urllib.request.Request(url, headers={"User-Agent": "assignment2-wikiart-classifier/1.0"})
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            content_type = response.headers.get("Content-Type", "image/jpeg").split(";")[0]
            return response.read(), content_type
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} while downloading image: {detail}") from exc


def find_image_url(value) -> str | None:
    if isinstance(value, dict):
        src = value.get("src")
        if isinstance(src, str) and src.startswith("http"):
            return src
        for nested in value.values():
            found = find_image_url(nested)
            if found:
                return found
    if isinstance(value, list):
        for nested in value:
            found = find_image_url(nested)
            if found:
                return found
    return None


def image_extension(content_type: str) -> str:
    if "png" in content_type:
        return ".png"
    if "webp" in content_type:
        return ".webp"
    return ".jpg"


def normalize_image_mime_type(content_type: str, image_url: str) -> str:
    guessed = mimetypes.guess_type(urllib.parse.urlparse(image_url).path)[0]
    if content_type.startswith("image/"):
        return content_type
    return guessed or "image/jpeg"


def fetch_dataset_rows(count: int) -> list[dict]:
    params = {**DATASET_PARAMS, "length": count}
    url = f"{DATASET_ROWS_URL}?{urllib.parse.urlencode(params, quote_via=urllib.parse.quote, safe='/')}"
    payload = request_json(url)
    rows = payload.get("rows", [])
    if not rows:
        raise RuntimeError("No rows returned from the Hugging Face datasets HTTP API.")
    return rows


def save_sample_images(count: int) -> list[dict]:
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    rows = fetch_dataset_rows(count)
    samples = []
    for sample_number, item in enumerate(rows, start=1):
        row = item.get("row", item)
        image_url = find_image_url(row)
        if not image_url:
            raise RuntimeError(f"Could not find an image URL in row {sample_number}.")

        image_content, raw_mime_type = download_bytes(image_url)
        mime_type = normalize_image_mime_type(raw_mime_type, image_url)
        image_name = f"wikiart_{sample_number:03d}{image_extension(mime_type)}"
        image_path = IMAGE_DIR / image_name
        image_path.write_bytes(image_content)
        samples.append(
            {
                "sample_id": sample_number,
                "dataset_index": item.get("row_idx", sample_number - 1),
                "image_file": f"images/{image_name}",
                "image_url": image_url,
                "mime_type": mime_type,
            }
        )
    return samples


def parse_classification_response(response_payload: dict, sample: dict) -> dict:
    content = response_payload["choices"][0]["message"].get("content")
    if content is None:
        print("Raw API response with empty content:")
        print(json.dumps(response_payload, indent=2, ensure_ascii=False))
        raise ValueError("API response content was empty")
    parsed = content if isinstance(content, dict) else json.loads(content)
    return {**sample, **parsed}


def build_payload(sample: dict, model: str) -> dict:
    image_path = OUTPUT_DIR / sample["image_file"]
    prompt_text = "Classify this WikiArt image for human, animal, flower, and AI-generated appearance."
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": prompt_text,
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": encode_image_as_data_url(image_path, sample.get("mime_type"))},
                    },
                ],
            },
        ],
        "response_format": {
            "type": "json_schema",
            "json_schema": CLASSIFICATION_SCHEMA,
        },
        "provider": {
            "require_parameters": True,
        },
        "temperature": 0,
        "max_tokens": 300,
    }
    return payload


def classify_image(api_key: str, sample: dict) -> dict:
    last_error = None
    models = [MODEL, *FALLBACK_MODELS]
    for model in models:
        try:
            response_payload = request_json(
                "https://openrouter.ai/api/v1/chat/completions",
                method="POST",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "HTTP-Referer": "https://github.com/",
                    "X-Title": "Assignment 2 Schema-Guided WikiArt Classification",
                },
                payload=build_payload(sample, model),
            )
            result = parse_classification_response(response_payload, sample)
            result["model_used"] = model
            if model != MODEL:
                result["status"] = "ok_after_model_fallback"
            return result
        except Exception as exc:
            last_error = exc
            print(f"{model} schema-guided attempt failed for sample {sample['sample_id']}: {exc}")
        if model != models[-1]:
            time.sleep(2)
    raise RuntimeError(f"All schema-guided classification attempts failed: {last_error}") from last_error


def skipped_result(sample: dict, reason: str, status: str = "skipped") -> dict:
    return {
        **sample,
        "has_human": "no",
        "has_animal": "no",
        "has_flower": "no",
        "looks_ai_generated": "no",
        "reason": reason,
        "ai_reason": reason,
        "status": status,
    }


def load_existing_results() -> dict[int, dict]:
    if not RESULTS_JSON.exists():
        return {}
    try:
        results = json.loads(RESULTS_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return {
        int(item["sample_id"]): item
        for item in results
        if isinstance(item, dict) and "sample_id" in item
    }


def render_html(results: list[dict]) -> str:
    cards = []
    for item in results:
        ai_badge = '<span class="badge ai">🤖 AI Suspected</span>' if item["looks_ai_generated"] == "yes" else ""
        cards.append(
            f"""
            <article class="card">
              <div class="image-wrap">
                {ai_badge}
                <img src="{html.escape(item["image_file"])}" alt="WikiArt sample {item["sample_id"]}">
              </div>
              <div class="card-body">
                <h2>Sample {item["sample_id"]}</h2>
                <div class="labels">
                  <span>Human: <strong>{html.escape(item["has_human"])}</strong></span>
                  <span>Animal: <strong>{html.escape(item["has_animal"])}</strong></span>
                  <span>Flower: <strong>{html.escape(item["has_flower"])}</strong></span>
                  <span>AI-like: <strong>{html.escape(item["looks_ai_generated"])}</strong></span>
                </div>
                <p><strong>Classification reason:</strong> {html.escape(item["reason"])}</p>
                <p><strong>AI appearance reason:</strong> {html.escape(item["ai_reason"])}</p>
              </div>
            </article>
            """
        )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Assignment 2 - WikiArt Image Classification</title>
  <style>
    body {{
      margin: 0;
      font-family: Arial, sans-serif;
      background: #f6f4ef;
      color: #202124;
    }}
    main {{
      max-width: 1180px;
      margin: 0 auto;
      padding: 32px 20px 48px;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 28px;
    }}
    p {{
      margin: 0 0 24px;
      color: #555;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
      gap: 18px;
    }}
    .card {{
      overflow: hidden;
      background: #fff;
      border: 1px solid #ddd8cd;
      border-radius: 8px;
    }}
    .image-wrap {{
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 240px;
      background: #f1eee8;
    }}
    img {{
      width: 100%;
      height: 240px;
      object-fit: contain;
    }}
    .badge {{
      position: absolute;
      top: 12px;
      left: 12px;
      padding: 6px 10px;
      border-radius: 999px;
      font-size: 12px;
      font-weight: 700;
      background: #262626;
      color: #fff;
      box-shadow: 0 2px 8px rgb(0 0 0 / 18%);
    }}
    .card-body {{
      padding: 14px;
    }}
    h2 {{
      margin: 0 0 10px;
      font-size: 18px;
    }}
    .labels {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 8px;
      margin-bottom: 12px;
      font-size: 13px;
    }}
    .labels span {{
      padding: 7px 8px;
      background: #f6f4ef;
      border: 1px solid #e7e1d6;
      border-radius: 6px;
    }}
    .card p {{
      margin: 10px 0 0;
      color: #333;
      line-height: 1.45;
    }}
  </style>
</head>
<body>
  <main>
    <h1>WikiArt Schema-Guided Image Classification</h1>
    <p>Model: {html.escape(MODEL)} | Samples: {len(results)} | Student: 202403234 Jihyun Yang</p>
    <section class="grid">
      {"".join(cards)}
    </section>
  </main>
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--count", type=int, default=20)
    parser.add_argument("--skip-api", action="store_true", help="Only download sample images and make a placeholder HTML.")
    args = parser.parse_args()

    load_env_file(OUTPUT_DIR / ".env")
    api_key = os.getenv("OPENROUTER_API_KEY")

    samples = save_sample_images(args.count)
    existing_results = load_existing_results()
    results = []

    if args.skip_api:
        for sample in samples:
            results.append(
                {
                    **sample,
                    "has_human": "no",
                    "has_animal": "no",
                    "has_flower": "no",
                    "looks_ai_generated": "no",
                    "reason": "Placeholder only. Run without --skip-api to classify this image.",
                    "ai_reason": "Placeholder only. Run without --skip-api to judge AI-like visual characteristics.",
                }
            )
    else:
        if not api_key:
            raise RuntimeError("OPENROUTER_API_KEY is missing. Create .env with OPENROUTER_API_KEY=your_token")
        for sample in samples:
            sample_id = sample["sample_id"]
            if sample_id in existing_results and existing_results[sample_id].get("status") not in {
                "skipped",
                "skipped_error",
                "skipped_empty_content",
            }:
                print(f"Using existing result for sample {sample_id}/{len(samples)}")
                results.append(existing_results[sample_id])
                continue

            print(f"Classifying sample {sample_id}/{len(samples)}")
            try:
                results.append(classify_image(api_key, sample))
            except KeyboardInterrupt:
                print("Interrupted. Saving partial results before exiting.")
                break
            except Exception as exc:
                print(f"Skipping sample {sample_id} after error: {exc}")
                results.append(skipped_result(sample, f"Skipped because classification failed: {exc}", "skipped_error"))
            RESULTS_JSON.write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")
            RESULTS_HTML.write_text(render_html(results), encoding="utf-8")
            time.sleep(1)

    RESULTS_JSON.write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")
    RESULTS_HTML.write_text(render_html(results), encoding="utf-8")
    print(f"Wrote {RESULTS_HTML}")


if __name__ == "__main__":
    main()
